version: '3.9'

services:
  api:
    build: .
    container_name: socialnetwork_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=socialnetwork;Username=postgres;Password=postgres
      - Jwt__Key=mysupersecretkeymysupersecretkey1234
    depends_on:
      - db
    networks:
      - socialnet
    restart: always

  db:
    image: postgres:16
    container_name: socialnetwork_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialnetwork
    ports:
      - "5432:5432"
    networks:
      - socialnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Migrations/complete_schema.sql:/docker-entrypoint-initdb.d/complete_schema.sql

  nginx:
    image: nginx:latest
    container_name: socialnetwork_nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - socialnet
    restart: always

  jmeter:
    image: justb4/jmeter:5.5
    container_name: jmeter
    volumes:
      - ./jmeter:/jmeter/project
    working_dir: /jmeter/project
    networks:
      - socialnet

  # (опц.) Для запуска GUI через VNC (если потребуется)
  # jmeter-gui:
  #   image: qnib/plain-jmeter
  #   container_name: jmeter-gui
  #   ports:
  #     - "5901:5901"
  #     - "6080:6080"
  #   environment:
  #     - VNC_RESOLUTION=1280x1024
  #   networks:
  #     - socialnet

networks:
  socialnet:
    driver: bridge

volumes:
  postgres_data:
